In [1]:
import pickle
from typing import List
def open_pkl(filename: str) -> List: 
    f = open(filename, 'rb')
    elementList = []
    while (True):
        try:
            data = pickle.load(f)
            elementList.append(data)
        except EOFError:
            return elementList

In [3]:
%pwd

'c:\\AttCRISPR\\Train'

In [2]:
WT_DATA_PATH = ".\WTData.pkl"
ESP_DATA_PATH = ".\ESPData.pkl"
SP_DATA_PATH = ".\SPData.pkl"

In [4]:
wt_dataset = open_pkl(WT_DATA_PATH)


In [31]:
import numpy as np
np.unique(wt_dataset[3],return_counts=True)

(array([1, 2, 3, 4], dtype=int64),
 array([241981, 321522, 292122, 312059], dtype=int64))

In [52]:
wt_dataset[3][0]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 3, 3, 2, 2, 2, 2, 3, 3, 3, 1],
      dtype=int64)

In [56]:
wt_dataset[0][0].reshape((1,21,4,1))

array([[[[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         [1]],

        [[0],
         [1],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         [1]],

        [[0],
         [0],
         [0],
         [1]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[0],


In [11]:
wt_dataset.shape

(55604, 21, 4, 1)

In [19]:
wt_dataset[0][0][0]

array([1])

In [49]:
esp_dataset = open_pkl(ESP_DATA_PATH)
esp_dataset

[array([[[[1],
          [0],
          [0],
          [0]],
 
         [[1],
          [0],
          [0],
          [0]],
 
         [[1],
          [0],
          [0],
          [0]],
 
         ...,
 
         [[0],
          [0],
          [0],
          [1]],
 
         [[0],
          [0],
          [0],
          [1]],
 
         [[0],
          [1],
          [0],
          [0]]],
 
 
        [[[1],
          [0],
          [0],
          [0]],
 
         [[1],
          [0],
          [0],
          [0]],
 
         [[1],
          [0],
          [0],
          [0]],
 
         ...,
 
         [[0],
          [0],
          [0],
          [1]],
 
         [[1],
          [0],
          [0],
          [0]],
 
         [[1],
          [0],
          [0],
          [0]]],
 
 
        [[[1],
          [0],
          [0],
          [0]],
 
         [[1],
          [0],
          [0],
          [0]],
 
         [[1],
          [0],
          [0],
          [0]],
 
         ...,
 
 

In [53]:
esp_dataset[3].shape

(58617, 21)

In [10]:
sp_dataset = open_pkl(SP_DATA_PATH)
sp_dataset

array([[[[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         [1]],

        [[0],
         [0],
         [0],
         [1]],

        [[0],
         [1],
         [0],
         [0]]],


       [[[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         [1]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]]],


       [[[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        [[1],
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         [1]],

        [[0],
         [0]

In [12]:
sp_dataset.shape

(56888, 21, 4, 1)

In [7]:
import numpy as np
score = [[1, 2, 3, 4],
         [1, 1, 3, 5],]
print(np.mean(score, axis=0))

[1.  1.5 3.  4.5]
